Update build-and-lint.yml

diff --git a/.github/workflows/build-and-lint.yml b/.github/workflows/build-and-lint.yml
--- a/.github/workflows/build-and-lint.yml
+++ b/.github/workflows/build-and-lint.yml
@@ -10,32 +10,38 @@ jobs:
   build-and-lint:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
-      
+      - name: Checkout code
+        uses: actions/checkout@v4
+
       - name: Install tools
         run: |
           sudo apt-get update
-          sudo apt-get install -y clang-format-18 clang-tidy-18
-          sudo ln -sf /usr/bin/clang-format-18 /usr/bin/clang-format
-          sudo ln -sf /usr/bin/clang-tidy-18 /usr/bin/clang-tidy
-          sudo ln -sf /usr/bin/run-clang-tidy-18 /usr/bin/run-clang-tidy
-      
-      - name: Check format
+          sudo apt-get install -y clang-tidy clang-format cmake
+
+      - name: Configure CMake
         run: |
-          find . -path ./build -prune -o -type f -name '*.[c|h]' -print | xargs clang-format --style=file --dry-run -Werror
-      
-      - name: Configure
+          PROJECT_ROOT=$(find . -name "CMakeLists.txt" -printf '%h' -quit)
+          
+          if [ -z "$PROJECT_ROOT" ]; then
+            echo "Error: CMakeLists.txt не найден в репозитории!"
+            exit 1
+          fi
+          
+          echo "Проект найден в папке: $PROJECT_ROOT"
+          cmake -S "$PROJECT_ROOT" -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
+
+      - name: clang-tidy
         run: |
-          cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
-      
+          run-clang-tidy -p build -checks='-*,bugprone-*,cert-*,clang-analyzer-*,misc-*,performance-*,readability-*,-clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling'
+
+      - name: clang-format
+        run: |
+          find . -path ./build -prune -o -name '*.[ch]' -print | xargs clang-format --dry-run --style=WebKit --Werror
+
       - name: Build
         run: |
           cmake --build build
-      
-      - name: Lint
+
+      - name: Run tests
         run: |
-          run-clang-tidy -p=build
-      
-      - name: Test
-        run: |
-          cd build && ctest --output-on-failure
+          find build -name "test*" -type f -executable -exec {} +
